### ISSUE TITLE
短时间之内掉线

### ISSUE THREAD

**Issue by rve** [humiaozuzu/YaH3C#11]
``` html
接入时长(秒)   服务名   
215                学生上网服务   
2630          学生上网服务    
45                学生上网服务    
```

下线原因:  NAS Error
环境： Arch

**Comment by huangjj27** [comment]
2016-07-04 出现同样的问题,几乎是没10分钟就会断一次，求开发迅速解决！
环境：ubuntu mate16.04（u盘系统）
browser： chrome Version 51.0.2704.106 (64-bit)
